=== ebhgw/sapmop509/database/examples/hierarchy_2.0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
The XML file must contain a "hierarchy" element that
surrounds one or more groups, generators or filters.
-->

<!ELEMENT hierarchy (group|filter|generator|test)+ >
<!ATTLIST hierarchy
     case (yes|no) "yes">
<!-- 

A "group" is a named element whose contents are controlled by the 
filter(s) defined within it.  If no filters are defined, then all alarms 
are attached to the group.  Groups can contain other groups, but the 
contained groups will only see the subset of alarms that passed their 
parent group's filter(s), if any.  You name the group with its "name" 
attribute.  The class of element is given by the "class" attribute.  This 
is useful for choosing a nice icon for the group, adding popup menu 
operations, and other class-sensitive features.  The "affected" attribute 
gives you a way to say that the affected element for this alarm is 
potentially this group, if no more detailed element claims the alarm 
instead.  
--> 

<!ELEMENT group (filter|fref|group|generator|param|properties|pref)* >
<!ATTLIST group
     name CDATA #REQUIRED
     class CDATA #REQUIRED
     affected (yes|no) "no"
     rollup CDATA #IMPLIED
     rollupParameters CDATA #IMPLIED> 

<!--
A "filter" controls which alarms can be attached to a group or generator 
element.  One or more filters are specified, and either all of the filters 
must pass (when the group's operator is and) or any of the filters must 
pass (when the group's operator is or).  A filter can test an alarm's 
fields, or it can test other information known when new alarms arrive.  
If you give a name to a filter, then you can reuse it in groups and 
generators defined later, using the fref element.  Filters can contain 
other filters or frefs, so you can build complex, multipart tests for 
inclusion.  
--> 

<!ELEMENT filter (filter|fref|field|test|tref)+ >
<!ATTLIST filter
    name CDATA #IMPLIED
    operator (and|or) "and"
    invert (true|false) "false">

<!-- 
A "field" is a test of a field within the incoming alarm.  You can 
choose one of the named fields, and compare its value using one of the 
specified operators.  You can compare it to the "value" attribute.  The 
"invert" attribute can invert the result of the true/false comparison.
--> 

<!ELEMENT field EMPTY>
<!ATTLIST field
    name CDATA #REQUIRED
    operator (
        equals|
        less|
        less_or_equals|
        greater|
        greater_or_equals|
        contains|
        starts_with|
        ends_with) "equals"
    value CDATA #REQUIRED
    case (yes|no) #IMPLIED
    invert (true|false) "false">

<!--
A "test" is a test of the alarm's affected element.  You can test whether 
an element has a specific capability (such as "console"), or you can run a 
script to evaluate some script fragment, which should return a boolean 
result.  You can say invert="true" to invert the result.
--> 

<!ELEMENT test (#PCDATA) >
<!ATTLIST test
    name CDATA #IMPLIED
    type (element|script|code) #REQUIRED
    expr CDATA #IMPLIED
    invert (true|false) "false">

<!-- 
An "fref" (filter reference) is used to refer to a filter that was 
previously defined.  The name attribute will refer to the name of a 
previously defined filter, so you can reuse a filter multiple times.  
--> 

<!ELEMENT fref EMPTY>
<!ATTLIST fref
    name CDATA #REQUIRED>

<!-- 
A "tref" (test reference) is used to refer to a test that was
previously defined.  The name attribute will refer to the name of a 
previously defined test, so you can reuse a test multiple times.
--> 

<!ELEMENT tref EMPTY>
<!ATTLIST tref
    name CDATA #REQUIRED>
        
<!-- 
A "generator" is a way to dynamically create new elements when alarms 
arrive, based on the value of the alarms' fields.  A new element will be 
created when a new, distinct field value arrives.  As with groups, you 
can choose the class to use with the "class" attribute.  Or, you could say 
that the generated element's class is derived from another alarm field's 
value, if you use the class_from_field attribute instead of the class 
attribute.  You would name the field to use as the class_from_field's 
value.  Because this dynamic mechanism could result in an unlimited number 
of generated elements over time, the "hold" attribute can be used to cause 
generated elements to age out after a period of time specified in the 
adapter settings.  Like groups, you can specify that generated elements 
are the affected elements of new alarms.  
--> 

<!ELEMENT generator (filter|fref|generator|group|param|properties|pref)* >
<!ATTLIST generator
    field CDATA #REQUIRED
    class CDATA #IMPLIED
    class_from_field CDATA #IMPLIED
    hold (yes|no) "no"
    affected (yes|no) "no"
    case (yes|no) #IMPLIED
    maxdepth CDATA #IMPLIED
    parentfield CDATA #IMPLIED
    rollup CDATA #IMPLIED
    rollupParameters CDATA #IMPLIED>

<!--
A "param" is an arbitrary parameter which can be assigned to elements.
Adapters use params to support adapter-specific behavior.
--> 

<!ELEMENT param EMPTY>
<!ATTLIST param
    name CDATA #REQUIRED
    value CDATA #REQUIRED>

<!--
A "properties" is a container for a group of "page" tags. It can
optionally be named, which allows a "pref" tag to reference the
named "properties" tag and effectively re-use its definition.
--> 

<!ELEMENT properties (page)+ >
<!ATTLIST properties
    name CDATA #IMPLIED
>

<!--
A "pref" is a properties reference. It references, by name, a "properties"
tag, which contains a definition of one or more element properties.
Referencing a "properties" tag with a "pref" is effectively re-using the
"properties" definition at the point of the "pref".
--> 

<!ELEMENT pref EMPTY >
<!ATTLIST pref
    name CDATA #IMPLIED
>

<!--
A "page" allows grouping the "property" and "value" tags it contains to a
specific named page for visual presentation in the client. If a name is not
given, the default page will be used.
--> 

<!ELEMENT page (property|value)+ >
<!ATTLIST page
    name CDATA #IMPLIED
>

<!--
A "property" defines, for a group or generated element, an element property
with a value to be computed from an alarm field for the alarm creates,
updates, and deletes it receives. "name" is the name of the property.
"field" is the alarm field used to compute the value. "function" is the type
of computation to be used on the field, with the value assigned to the named
property. "parameter" is a parameterized value passed to the function.
"parameter" is used by the "ROLLINGAVG" and PSEUDOAVG" functions to indicate
how many values to keep in the average. "computeOnGet" (default false) false
to compute the value on alarm creates, updates, and deletes for alarms attaching
to the element. If true, iterate over alarms and compute the value only when the
value is needed (i.e. for a property page or on getAttr()). "computeOnNoAlarms"
(default is null) if set will set the property to the supplied value if no alarms
are present, however, if not set, it will pick up the value of the last alarm
deleted when no alarms are present. "computeLastDateTimeStampField" (default is null)
is only used if LAST or LASTWITHVALUE are set, and if set will be the alarm field value 
analyzed to determine if the last alarm date and time stamp is later than the one used
for setting this property, then it will elevate this alarm property value, otherwise,
it will ignore the alarm transaction - NOTE: the base behavior is strictly last
alarm transaction received has the property elevated.

The custom Property values are taken from the alarm field when a compute of the
custom property is triggered. The triggers are alarm create, change, or delete
against the element.

(O) The value of the alarm field is left as is and no conversions are done.
(A) The value of the alarm field is interpreted as string data
(N) The value of the alarm field is interpreted as numeric data. If the alarm
    field is a string, an attempt will be made to convert it into a numeric value.

LAST -    (O) Alarm field value for most recent alarm create, change, delete
              against the element.
LASTWITHVALUE - 
          (O) Alarm field value for most recent alarm create, change, delete
              against the element if the field is in the alarm.
FIRST -   (O) Alarm field value for first alarm create, change, delete against
              the element.
AVG -     (N) Alarm field value averaged over all existing alarms against the element.
SUM -     (N) Alarm field value summed over all existing alarms against the element.
ROLLINGAVG - (N) Alarm field value averaged over the last n (where n is given in the
                 "parameter" attribute) alarm creates and changes (but not deletes)
                 against the element. n defaults to 10.
PSEUDOAVG -  (N) Alarm field value pseudo-averaged over the last n (where n is given
                 in the "parameter" attribute) alarm creates and changes (but not
                 deletes) against the element. n defaults to 10.
LOWEST -  (A) Alarm field value minimum in alphnumeric sort order across all
              alarm creates, changes, deletes against the element.
HIGHEST - (A) Alarm field value maximum in alphnumeric sort order across all
              alarm creates, changes, deletes against the element.
MIN -     (N) Alarm field value minimum in numeric order across all alarm creates,
              changes, deletes against the element.
MAX -     (N) Alarm field value maximum in numeric order across all alarm creates,
              changes, deletes against the element.

Notes on property's:
- You do not want to re-use the same name across custom property pages.
- You do not want to re-use the same name as a Formula Property (i.e. Element, Condition, etc)
- You do not want to have two custom property's computing the same function against the same alarm field.
- If a property is computed against an alarm field, then that alarm field is mandatory.

--> 

<!ELEMENT property EMPTY >
<!ATTLIST property
    name CDATA #REQUIRED
    field CDATA #REQUIRED
    function (LAST|FIRST|AVG|SUM|LOWEST|HIGHEST|MIN|MAX|ROLLINGAVG|PSEUDOAVG|LASTWITHVALUE) #REQUIRED
    parameter CDATA #IMPLIED
    computeOnGet (true|false) "false"
    computeOnNoAlarms CDATA #IMPLIED
    computeLastDateTimeStampField CDATA #IMPLIED
>

<!--
A "value" defines, for a group or generated element, an element property
to be created with a literal value.
--> 

<!ELEMENT value EMPTY >
<!ATTLIST value
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

=== ebhgw/sapmop509/database/examples/ServiceManagerHierarchy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hierarchy PUBLIC "-//Novell, Inc.//DTD hierarchy 2.0//EN" "database/examples/hierarchy_2.0.dtd">


<!--
 Copyright (c) 2014 NetIQ Corporation.  All Rights Reserved.

 THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND TREATIES.  IT MAY NOT BE USED, COPIED,
 DISTRIBUTED, DISCLOSED, ADAPTED, PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT NETIQ'S
 PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE
 PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.

 NETIQ PROVIDES THE WORK "AS IS," WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING WITHOUT THE
 IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NETIQ,
 THE AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT LIABLE FOR ANY CLAIM,
 DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF,
 OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
-->


<!--
     Please refer to the hierarchy.dtd file in your Formula(tm)
     installation directory for details on the definition of this file.
     
     In this file, you can specify alarm fields in order to generate
     new elements or compare field values.
     
     The fields normalized from a Peregrine ServiceCenter Module and available as an
     alarm field value are:

     Field Name          Config XML Element    Value
     ==========          ==================    =====
     _SC_RECORD_KEY      <key>                 The record id.
     _SC_LAST_UPDATE     <lastUpdate>          The time the record was last updated.
     _SC_MODULE_NAME     N/A                   The Module name. Will be "Incident" for the configuration file example below.
     _SC_DESCRIPTION     <description>         The record description.
     _SC_ASSIGNED_TO     <assignedTo>          "Person" assigned to the record.
     _SC_SEVERITY_NAME   N/A                   Derived by Formula based on the <status> field and the <severities> mappings
                                               in the configuration file.
     _SC_STATUS          <status>              The current status of the record. I.e. open, reopened, resolved, etc.
     
     The above fields are identified in the configuration file by the given Config XML elements for each
     Module. For example,
          <module name="Incident" enable="true">
                ....
                <properties>
                     <formula>
                          <fields>
                               <status>status</status>
                               <lastUpdate>update.time</lastUpdate>
                               <key>number</key>
                               <description>brief.description</description>
                               <assignedTo>assignee.name</assignedTo>
                          </fields>
                ....

     Also, any ServiceCenter Module field returned by ServiceCenter can be used as an alarm field value.
     An example may be the 'header.number' field from the Change Management Module. You can determine the
     fields returned by ServiceCenter by right-clicking on a desired Formula Alarm and selecting the
     "Properties" menu item. Then select the "All Fields" property page.

-->

<hierarchy>
    <group name="Modules" class="applications">
        <generator field="_SC_MODULE_NAME" class="application" affected="yes">
           <group name="Severities" class="barIndet">
               <group name="Critical/Fatal" class="barCritical">
                   <filter>
                       <field name="_SC_SEVERITY_NAME" value="Critical" />
                   </filter>
               </group>
               <group name="Info" class="barHarmless">
                   <filter>
                       <field name="_SC_SEVERITY_NAME" value="Info" />
                   </filter>
               </group>
               <group name="Minor" class="barMinor">
                   <filter>
                       <field name="_SC_SEVERITY_NAME" value="Minor" />
                   </filter>
               </group>
               <group name="Ok" class="barOK">
                   <filter>
                       <field name="_SC_SEVERITY_NAME" value="Ok" />
                   </filter>
               </group>
               <group name="Major" class="barWarning">
                   <filter>
                       <field name="_SC_SEVERITY_NAME" value="Major" />
                   </filter>
               </group>
           </group>
           <group name="Assigned To" class="admin_users">
               <generator field="_SC_ASSIGNED_TO" class="admin_user" affected="yes"/>
           </group>
           <group name="Status" class="gen_folder">
               <generator field="_SC_STATUS" class="gen_alert"/>
           </group>
        </generator>
    </group>

</hierarchy>

=== ebhgw/sapmop509/database/examples/FXAdapterHierarchy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE hierarchy PUBLIC "-//Novell, Inc.//DTD hierarchy 2.0//EN" "http://www.novell.com/dtds/hierarchy_2.0.dtd">
-->

<!--
 Copyright (c) 2014 NetIQ Corporation.  All Rights Reserved.

 THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND TREATIES.  IT MAY NOT BE USED, COPIED,
 DISTRIBUTED, DISCLOSED, ADAPTED, PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT NETIQ'S
 PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE
 PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.

 NETIQ PROVIDES THE WORK "AS IS," WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING WITHOUT THE
 IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NETIQ,
 THE AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT LIABLE FOR ANY CLAIM,
 DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF,
 OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
-->
<!--
     Please refer to the hierarchy.dtd file in your Formula(tm)
     installation directory for details on the definition of this file.
     
     In this file, you can specify alarm fields in order to generate
     new elements or compare field values.
     
     The fields available for the Script adapter are:

     Field Name     Value
     ==========     =====
     id             alarm ID (internal to Formula)
     
     Also, any slot name can be used as an alarm field value.
     
-->
<hierarchy case="no">

    <group class="gen_folder" name="Data">
        <generator class="gen_file" field="FilePath" hold="yes"/>
        <filter name="filter.data">
            <field case="no" name="ALARM_TYPE" value="data"/>
        </filter>
    </group>
    <group class="server_hosts" name="Monitors">
        <properties name="thing">
            <page name="Properties">
                <property field="dummy" function="LAST" name="Overlapping"/>
            </page>
        </properties>
        <generator affected="yes" class="server_file" field="MonitorHost">
            <generator class="mgmt_source" field="ParserName"/>
        </generator>
        <filter name="filter.status">
            <field case="no" name="ALARM_TYPE" value="STATUS"/>
        </filter>
        <param name="thing" value="dummy"/>
    </group>
    <group class="gen_folder_shared" name="File Information">
        <generator affected="no" class="gen_folder" field="FileDirectory" hold="no">
            <generator class="gen_file" field="FilePath"/>
        </generator>
        <filter invert="false" name="filter.fileinfo" operator="and">
            <field case="no" name="ALARM_TYPE" value="fileinfo"/>
        </filter>
    </group>
</hierarchy>

=== ebhgw/sapmop509/database/BDIImportDataHierarchy.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE hierarchy PUBLIC "-//Novell, Inc.//DTD hierarchy 2.0//EN" "http://www.Novell.com/dtds/hierarchy_2.0.dtd">
<hierarchy>

<!--
   This Hierarchy File is automatically generated by BDI to allow the BDI Definition to function properly.
   Do not hand edit this Hierarchy File or the BDI Integration may not function properly.
   Any desired modifications should be made within the BDI IDE and the definition re-deployed.
-->


<!--Top-level Hierarchy XML Start-->
q
<!--Top-level Hierarchy XML End-->

  <group affected="no" class="_ID21_Services" name="Services">
    <generator affected="yes" class="_ID23_Sistema" field="_ID23_ChiaveSistema">
      <generator affected="yes" class="_ID24_Sottosistema" field="_ID24_SottosistemaKey" hold="yes">
        <generator affected="yes" class="_ID25_Application" field="_ID25_ApplicationKey" hold="yes">
          <generator affected="yes" class="_ID26_Tecnologico" field="_ID26_ChiaveTecnologico">
            <generator affected="yes" class="_ID27_Infrastruttura" field="_ID27_InfrastrutturaKey" hold="yes"/>
          </generator>
        </generator>
      </generator>
    </generator>
  </group>
  <group affected="no" class="_ID22_Servers" name="Servers">
    <generator affected="yes" class="_ID32_Servers" field="_ID32_ServersKey" hold="yes"/>
  </group>
  <group affected="no" class="_ID35_Relations" name="Relations">
    <generator affected="yes" class="_ID36_Rel_HW2Infra" field="_ID36_chiaveD"/>
    <generator affected="yes" class="_ID30_Rel_ClusterServer" field="_ID30_ChiaveRel"/>
  </group>
  <group affected="no" class="_ID11_Dashboard" name="Dashboard">
    <generator affected="yes" class="_ID12_LivelloSistema" field="_ID12_ChiaveSistema">
      <generator affected="yes" class="_ID16_LivelloSottoSistema" field="_ID16_LivelloSottoSistemaKey" hold="yes">
        <generator affected="yes" class="_ID17_LivelloApplication" field="_ID17_LivelloApplicationKey" hold="yes">
          <generator affected="yes" class="_ID18_LivelloClasseInfra" field="_ID18_ChiaveClasseInfra">
            <generator affected="yes" class="_ID19_LivelloInfrastrutturale" field="_ID19_LivelloInfrastrutturaleKey" hold="yes">
              <generator affected="yes" class="_ID20_LivelloServer" field="_ID20_LivelloServerKey" hold="yes"/>
            </generator>
          </generator>
        </generator>
      </generator>
    </generator>
  </group>
  <group affected="no" class="_ID0_Import_Data" name="Import Data">
    <generator affected="yes" class="_ID7_ISP_AmbitoCluster" field="_ID7_CIAmbito">
      <generator affected="yes" class="_ID8_ISP_Servizio" field="_ID8_CIServizio">
        <generator affected="yes" class="_ID9_ISP_AreaTecnologica" field="_ID9_CIAreaTecnologica">
          <generator affected="yes" class="_ID10_ISP_LivelloArchitettura" field="_ID10_CIArchitettura">
            <generator affected="yes" class="_ID13_ISP_Cluster" field="_ID13_CICLuster">
              <generator affected="yes" class="_ID14_ISP_Server" field="_ID14_ISP_ServerKey" hold="yes">
                <generator affected="yes" class="_ID15_ISP_Risorsa" field="_ID15_ISP_RisorsaKey" hold="yes"/>
              </generator>
            </generator>
          </generator>
        </generator>
      </generator>
    </generator>
    <generator affected="yes" class="_ID1_ISP_Ambito" field="_ID1_CIAmbito">
      <generator affected="yes" class="_ID2_ISP_Servizio" field="_ID2_CIServizio">
        <generator affected="yes" class="_ID3_ISP_AreaTecnologica" field="_ID3_CIAreaTecnologica">
          <generator affected="yes" class="_ID4_ISP_LivelloArchitettura" field="_ID4_CIArchitettura">
            <generator affected="yes" class="_ID5_ISP_Server" field="_ID5_ServerKey" hold="yes">
              <generator affected="yes" class="_ID6_ISP_Risorsa" field="_ID6_DBElement1Key" hold="yes"/>
            </generator>
          </generator>
        </generator>
      </generator>
    </generator>
  </group>
  <group affected="no" class="_ID28_Clusters" name="Clusters">
    <generator affected="yes" class="_ID29_Cluster" field="_ID29_ClusterKey" hold="yes"/>
  </group>
</hierarchy>

=== ebhgw/sapmop509/database/examples/CICHierarchy.xml
<?xml version="1.0"?>
<!DOCTYPE hierarchy PUBLIC "-//Novell, Inc.//DTD hierarchy 2.0//EN" "database/examples/hierarchy_2.0.dtd">


<!--
 Copyright (c) 2014 NetIQ Corporation.  All Rights Reserved.

 THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND TREATIES.  IT MAY NOT BE USED, COPIED,
 DISTRIBUTED, DISCLOSED, ADAPTED, PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT NETIQ'S
 PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE
 PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.

 NETIQ PROVIDES THE WORK "AS IS," WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING WITHOUT THE
 IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NETIQ,
 THE AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT LIABLE FOR ANY CLAIM,
 DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF,
 OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
-->

<!--
     Please refer to the hierarchy.dtd file in your Formula(tm)
     installation directory for details on the definition of this file.
     
     In this file, you can specify alarm fields in order to generate
     new elements or compare field values.
     
     The fields available for Cisco Info Center(r) are:

        Field Name      Value
        ==========      =====
        Identifier      Internal hash key/table identifier
        Serial          Cisco Info Center(r) serial number item
        Node            Host or IP Address
        NodeAlias       Alias for Node
        Manager         Descriptive name of manager which generated the alert
        Agent           Descriptive name of sub manager which generated the alert
        AlertGroup      Descriptive name of group within the manager which generated the alert
        AlertKey        Descriptive key with reference to the alert
        Severity        Severity of problem
        Summary         Summary of alert problem
        StateChange     Timestamp of last insert/update of alert from any source
        FirstOccurrence Timestamp when this alert was created
        LastOccurrence  Time when this alert was last updated at the probe
        InternalLast    Time when this alert was last updated at the object server
        Poll            Frequency of polling for this alert (in seconds)
        Type            Type of alert
        Tally           Automatically maintained count of the number of inserts/updates of this alert from any source
        Class           Alert class
        Grade           Grade of the alert/problem within the set severity
        Location        Not used
        OwnerUID        User id of the user assigned to handle this alert
        OwnerGID        Group identifier of the group assigned to handle this alert
        Acknowledged    Has user acknowledged the assignment (0 - No, 1 - Yes)
        Flash           Enables the option to make the event list flash
        ServerName      Name of the originating server
        ServerSerial    Serial number of the alert on the originating server
     
-->

<hierarchy>

    <group name="Assignment" class="Assignment">
        <generator field="OwnerGID" class="Group" >
            <generator field="OwnerUID" class="User" />
        </generator>
    </group>
    
    <group name="Severities" class="Severities">
        <generator field="Severity" affected="no" class_from_field="Severity" >
                <generator field="Node" class="Node" />
        </generator>
    </group>

    <group name="Classes" class="Classes">
        <generator field="Class" class="Class" >
            <generator field="Node" class="Node" />
        </generator>
    </group>

    <group name="Nodes" class="Nodes">
        <generator field="Node" affected="yes" class="Node" />
    </group>

</hierarchy>

=== ebhgw/sapmop509/database/examples/FoundationHierarchy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hierarchy PUBLIC "-//Novell, Inc.//DTD hierarchy 2.0//EN" "database/examples/hierarchy_2.0.dtd">


<!--
 Copyright (c) 2014 NetIQ Corporation.  All Rights Reserved.

 THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND TREATIES.  IT MAY NOT BE USED, COPIED,
 DISTRIBUTED, DISCLOSED, ADAPTED, PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT NETIQ'S
 PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE
 PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.

 NETIQ PROVIDES THE WORK "AS IS," WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING WITHOUT THE
 IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NETIQ,
 THE AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT LIABLE FOR ANY CLAIM,
 DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF,
 OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
-->
<!--
     Please refer to the hierarchy.dtd file in your Formula(tm)
     installation directory for details on the definition of this file.

     In this file, you can specify alarm fields in order to generate
     new elements or compare field values.

     The fields available for Tideway Foundation using the default queries are:

     Field Name             Value
     ==========             =====
     
     The host.* properties correspond to columns returned from 'Host' type
     queries.  If you add/remove columns from the query they will be added/removed
     from the alarm properties available.
     
     Default values are;

     host.name				Host name
    
     service.SPVI			Software Instance Name	
     service.BAI			Business Application Instance in the format (Business App. Name/Business App. Type/Product Version)
     service.Host           Host Name

	 BAI                    Business Application Instance Name
	 SUBNET                 Subnet range
     SWITCH				    Switch
     
     * Note Tideway does not guarantee orientation of network connection information.

-->
<hierarchy>
	<group class="gen_folder" name="Components">
	<group class="gen_folder" name="Application Instance">
		<generator class="formula_organizations" field="BAI" />
	</group>
		<group class="gen_folder" name="Host">
			<generator class="admin_automation_server" field="host.name" />
	</group>
		<group class="gen_folder" name="Host and Software Instance">
			<generator class="admin_automation_server" field="service.Host">
				<generator class="admin_automation_repository" field="service.SPVI"/>
			</generator>
		</group>
	<group class="gen_folder" name="Software Instance">
		<generator class="admin_automation" field="service.SPVI" />
		</group>	
		<group class="gen_folder" name="Subnets">
			<generator class="net_lan" field="SUBNET" />
		</group>		
		<group class="gen_folder" name="Switches">
			<generator class="telcom_switch" field="SWITCH" />
		</group>		
	</group>
</hierarchy>
