=== ebhgw/sapmop509/database/examples/hierarchy_2.0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
The XML file must contain a "hierarchy" element that
surrounds one or more groups, generators or filters.
-->

<!ELEMENT hierarchy (group|filter|generator|test)+ >
<!ATTLIST hierarchy
     case (yes|no) "yes">
<!-- 

A "group" is a named element whose contents are controlled by the 
filter(s) defined within it.  If no filters are defined, then all alarms 
are attached to the group.  Groups can contain other groups, but the 
contained groups will only see the subset of alarms that passed their 
parent group's filter(s), if any.  You name the group with its "name" 
attribute.  The class of element is given by the "class" attribute.  This 
is useful for choosing a nice icon for the group, adding popup menu 
operations, and other class-sensitive features.  The "affected" attribute 
gives you a way to say that the affected element for this alarm is 
potentially this group, if no more detailed element claims the alarm 
instead.  
--> 

<!ELEMENT group (filter|fref|group|generator|param|properties|pref)* >
<!ATTLIST group
     name CDATA #REQUIRED
     class CDATA #REQUIRED
     affected (yes|no) "no"
     rollup CDATA #IMPLIED
     rollupParameters CDATA #IMPLIED> 

<!--
A "filter" controls which alarms can be attached to a group or generator 
element.  One or more filters are specified, and either all of the filters 
must pass (when the group's operator is and) or any of the filters must 
pass (when the group's operator is or).  A filter can test an alarm's 
fields, or it can test other information known when new alarms arrive.  
If you give a name to a filter, then you can reuse it in groups and 
generators defined later, using the fref element.  Filters can contain 
other filters or frefs, so you can build complex, multipart tests for 
inclusion.  
--> 

<!ELEMENT filter (filter|fref|field|test|tref)+ >
<!ATTLIST filter
    name CDATA #IMPLIED
    operator (and|or) "and"
    invert (true|false) "false">

<!-- 
A "field" is a test of a field within the incoming alarm.  You can 
choose one of the named fields, and compare its value using one of the 
specified operators.  You can compare it to the "value" attribute.  The 
"invert" attribute can invert the result of the true/false comparison.
--> 

<!ELEMENT field EMPTY>
<!ATTLIST field
    name CDATA #REQUIRED
    operator (
        equals|
        less|
        less_or_equals|
        greater|
        greater_or_equals|
        contains|
        starts_with|
        ends_with) "equals"
    value CDATA #REQUIRED
    case (yes|no) #IMPLIED
    invert (true|false) "false">

<!--
A "test" is a test of the alarm's affected element.  You can test whether 
an element has a specific capability (such as "console"), or you can run a 
script to evaluate some script fragment, which should return a boolean 
result.  You can say invert="true" to invert the result.
--> 

<!ELEMENT test (#PCDATA) >
<!ATTLIST test
    name CDATA #IMPLIED
    type (element|script|code) #REQUIRED
    expr CDATA #IMPLIED
    invert (true|false) "false">

<!-- 
An "fref" (filter reference) is used to refer to a filter that was 
previously defined.  The name attribute will refer to the name of a 
previously defined filter, so you can reuse a filter multiple times.  
--> 

<!ELEMENT fref EMPTY>
<!ATTLIST fref
    name CDATA #REQUIRED>

<!-- 
A "tref" (test reference) is used to refer to a test that was
previously defined.  The name attribute will refer to the name of a 
previously defined test, so you can reuse a test multiple times.
--> 

<!ELEMENT tref EMPTY>
<!ATTLIST tref
    name CDATA #REQUIRED>
        
<!-- 
A "generator" is a way to dynamically create new elements when alarms 
arrive, based on the value of the alarms' fields.  A new element will be 
created when a new, distinct field value arrives.  As with groups, you 
can choose the class to use with the "class" attribute.  Or, you could say 
that the generated element's class is derived from another alarm field's 
value, if you use the class_from_field attribute instead of the class 
attribute.  You would name the field to use as the class_from_field's 
value.  Because this dynamic mechanism could result in an unlimited number 
of generated elements over time, the "hold" attribute can be used to cause 
generated elements to age out after a period of time specified in the 
adapter settings.  Like groups, you can specify that generated elements 
are the affected elements of new alarms.  
--> 

<!ELEMENT generator (filter|fref|generator|group|param|properties|pref)* >
<!ATTLIST generator
    field CDATA #REQUIRED
    class CDATA #IMPLIED
    class_from_field CDATA #IMPLIED
    hold (yes|no) "no"
    affected (yes|no) "no"
    case (yes|no) #IMPLIED
    maxdepth CDATA #IMPLIED
    parentfield CDATA #IMPLIED
    rollup CDATA #IMPLIED
    rollupParameters CDATA #IMPLIED>

<!--
A "param" is an arbitrary parameter which can be assigned to elements.
Adapters use params to support adapter-specific behavior.
--> 

<!ELEMENT param EMPTY>
<!ATTLIST param
    name CDATA #REQUIRED
    value CDATA #REQUIRED>

<!--
A "properties" is a container for a group of "page" tags. It can
optionally be named, which allows a "pref" tag to reference the
named "properties" tag and effectively re-use its definition.
--> 

<!ELEMENT properties (page)+ >
<!ATTLIST properties
    name CDATA #IMPLIED
>

<!--
A "pref" is a properties reference. It references, by name, a "properties"
tag, which contains a definition of one or more element properties.
Referencing a "properties" tag with a "pref" is effectively re-using the
"properties" definition at the point of the "pref".
--> 

<!ELEMENT pref EMPTY >
<!ATTLIST pref
    name CDATA #IMPLIED
>

<!--
A "page" allows grouping the "property" and "value" tags it contains to a
specific named page for visual presentation in the client. If a name is not
given, the default page will be used.
--> 

<!ELEMENT page (property|value)+ >
<!ATTLIST page
    name CDATA #IMPLIED
>

<!--
A "property" defines, for a group or generated element, an element property
with a value to be computed from an alarm field for the alarm creates,
updates, and deletes it receives. "name" is the name of the property.
"field" is the alarm field used to compute the value. "function" is the type
of computation to be used on the field, with the value assigned to the named
property. "parameter" is a parameterized value passed to the function.
"parameter" is used by the "ROLLINGAVG" and PSEUDOAVG" functions to indicate
how many values to keep in the average. "computeOnGet" (default false) false
to compute the value on alarm creates, updates, and deletes for alarms attaching
to the element. If true, iterate over alarms and compute the value only when the
value is needed (i.e. for a property page or on getAttr()). "computeOnNoAlarms"
(default is null) if set will set the property to the supplied value if no alarms
are present, however, if not set, it will pick up the value of the last alarm
deleted when no alarms are present. "computeLastDateTimeStampField" (default is null)
is only used if LAST or LASTWITHVALUE are set, and if set will be the alarm field value 
analyzed to determine if the last alarm date and time stamp is later than the one used
for setting this property, then it will elevate this alarm property value, otherwise,
it will ignore the alarm transaction - NOTE: the base behavior is strictly last
alarm transaction received has the property elevated.

The custom Property values are taken from the alarm field when a compute of the
custom property is triggered. The triggers are alarm create, change, or delete
against the element.

(O) The value of the alarm field is left as is and no conversions are done.
(A) The value of the alarm field is interpreted as string data
(N) The value of the alarm field is interpreted as numeric data. If the alarm
    field is a string, an attempt will be made to convert it into a numeric value.

LAST -    (O) Alarm field value for most recent alarm create, change, delete
              against the element.
LASTWITHVALUE - 
          (O) Alarm field value for most recent alarm create, change, delete
              against the element if the field is in the alarm.
FIRST -   (O) Alarm field value for first alarm create, change, delete against
              the element.
AVG -     (N) Alarm field value averaged over all existing alarms against the element.
SUM -     (N) Alarm field value summed over all existing alarms against the element.
ROLLINGAVG - (N) Alarm field value averaged over the last n (where n is given in the
                 "parameter" attribute) alarm creates and changes (but not deletes)
                 against the element. n defaults to 10.
PSEUDOAVG -  (N) Alarm field value pseudo-averaged over the last n (where n is given
                 in the "parameter" attribute) alarm creates and changes (but not
                 deletes) against the element. n defaults to 10.
LOWEST -  (A) Alarm field value minimum in alphnumeric sort order across all
              alarm creates, changes, deletes against the element.
HIGHEST - (A) Alarm field value maximum in alphnumeric sort order across all
              alarm creates, changes, deletes against the element.
MIN -     (N) Alarm field value minimum in numeric order across all alarm creates,
              changes, deletes against the element.
MAX -     (N) Alarm field value maximum in numeric order across all alarm creates,
              changes, deletes against the element.

Notes on property's:
- You do not want to re-use the same name across custom property pages.
- You do not want to re-use the same name as a Formula Property (i.e. Element, Condition, etc)
- You do not want to have two custom property's computing the same function against the same alarm field.
- If a property is computed against an alarm field, then that alarm field is mandatory.

--> 

<!ELEMENT property EMPTY >
<!ATTLIST property
    name CDATA #REQUIRED
    field CDATA #REQUIRED
    function (LAST|FIRST|AVG|SUM|LOWEST|HIGHEST|MIN|MAX|ROLLINGAVG|PSEUDOAVG|LASTWITHVALUE) #REQUIRED
    parameter CDATA #IMPLIED
    computeOnGet (true|false) "false"
    computeOnNoAlarms CDATA #IMPLIED
    computeLastDateTimeStampField CDATA #IMPLIED
>

<!--
A "value" defines, for a group or generated element, an element property
to be created with a literal value.
--> 

<!ELEMENT value EMPTY >
<!ATTLIST value
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

=== ebhgw/sapmop509/database/examples/HPNNMiHierarchy.xml
<?xml version="1.0"?>
<!DOCTYPE hierarchy PUBLIC "-//Novell, Inc.//DTD hierarchy 2.0//EN" "database/examples/hierarchy_2.0.dtd">


<!--
 Copyright (c) 2014 NetIQ Corporation.  All Rights Reserved.

 THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND TREATIES.  IT MAY NOT BE USED, COPIED,
 DISTRIBUTED, DISCLOSED, ADAPTED, PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT NETIQ'S
 PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE
 PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.

 NETIQ PROVIDES THE WORK "AS IS," WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING WITHOUT THE
 IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NETIQ,
 THE AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT LIABLE FOR ANY CLAIM,
 DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF,
 OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
-->

<hierarchy>

 <group name="Inventory" class="gen_folder">
  <param name="AlarmColumns" value="-ID,Type=internalAlarmType,Name"/>

  <group name="Nodes By Status" class="gen_folder">
    <param name="AlarmColumns" value="-ID,Name,Status,Discovery State,Management Mode,Device Category Short,Device Description,Device Model,Device Family Short,Device Vendor Short,Uuid,Notes,Created,Modified"/>
    <filter>
       <field name="internalAlarmType" operator="equals" value="node"/>
    </filter>
    <generator field="status" class="gen_folder" affected="no">
       <param name="AlarmColumns" value="-ID,Name,Status,Discovery State,Management Mode,Device Category Short,Device Description,Device Model,Device Family Short,Device Vendor Short,Uuid,Notes,Created,Modified"/>
    </generator>
  </group>

  <group name="Node Groups By Status" class="gen_folder">
    <param name="AlarmColumns" value="-ID,Name,Status,Uuid,Created,Modified"/>
    <filter>
       <field name="internalAlarmType" operator="equals" value="nodegroup"/>
    </filter>
    <generator field="status" class="gen_folder" affected="no">
       <param name="AlarmColumns" value="-ID,Name,Status,Uuid,Created,Modified"/>
    </generator>
  </group>

  <group name="Interfaces By Status" class="gen_folder">
    <param name="AlarmColumns" value="-ID,Name,Status,Uuid,Created,Modified"/>
    <filter>
       <field name="internalAlarmType" operator="equals" value="interface"/>
    </filter>
    <generator field="status" class="gen_folder" affected="no">
       <param name="AlarmColumns" value="-ID,Name,Status,Uuid,Created,Modified"/>
    </generator>
  </group>

  <group name="IPSubnets" class="gen_folder">
    <param name="AlarmColumns" value="-ID,Name,Prefix,Prefix Length,Notes,Created,Modified"/>
    <filter>
       <field name="internalAlarmType" operator="equals" value="ipsubnet"/>
    </filter>
  </group>

  <group name="IPAddresses By Management Mode" class="gen_folder">
    <param name="AlarmColumns" value="-ID,IP Value,Management Mode,Notes,Created,Modified"/>
    <filter>
       <field name="internalAlarmType" operator="equals" value="ipaddress"/>
    </filter>
    <generator field="managementMode" class="gen_folder" affected="no">
       <param name="AlarmColumns" value="-ID,IP Value,Management Mode,Notes,Created,Modified"/>
    </generator>
  </group>

  <group name="L2Connections By Status" class="gen_folder">
    <param name="AlarmColumns" value="-ID,Name,Status,Notes,Created,Modified"/>
    <filter>
       <field name="internalAlarmType" operator="equals" value="l2connection"/>
    </filter>
    <generator field="status" class="gen_folder" affected="no">
       <param name="AlarmColumns" value="-ID,Name,Status,Notes,Created,Modified"/>
    </generator>
  </group>

 </group>

 <group name="Incidents" class="gen_folder">
  <filter>
     <field name="internalAlarmType" operator="equals" value="incident"/>
  </filter>

  <group name="Incidents By Severity" class="gen_folder">
    <param name="AlarmColumns" value="-ID,Message,Lifecycle State Short,Priority Short,Source Node Name,Assigned To,Category Short,Family Short,Nature,Origin,Origin Occurrence Time,First Occurrence Time,Last Occurrence Time,Duplicate Count,Uuid,Notes,Created,Modified"/>
    <generator field="severity" class="gen_folder" affected="no">
       <param name="AlarmColumns" value="-ID,Message,Lifecycle State Short,Priority Short,Source Node Name,Assigned To,Category Short,Family Short,Nature,Origin,Origin Occurrence Time,First Occurrence Time,Last Occurrence Time,Duplicate Count,Uuid,Notes,Created,Modified"/>
    </generator>
  </group>

  <group name="Incidents By Category" class="gen_folder">
    <param name="AlarmColumns" value="-ID,Message,Lifecycle State Short,Priority Short,Source Node Name,Assigned To,Category Short,Family Short,Nature,Origin,Origin Occurrence Time,First Occurrence Time,Last Occurrence Time,Duplicate Count,Uuid,Notes,Created,Modified"/>
    <generator field="categoryShort" class="gen_folder" affected="no">
       <param name="AlarmColumns" value="-ID,Message,Lifecycle State Short,Priority Short,Source Node Name,Assigned To,Category Short,Family Short,Nature,Origin,Origin Occurrence Time,First Occurrence Time,Last Occurrence Time,Duplicate Count,Uuid,Notes,Created,Modified"/>
    </generator>
  </group>

  <group name="Incidents By Priority" class="gen_folder">
    <param name="AlarmColumns" value="-ID,Message,Lifecycle State Short,Priority Short,Source Node Name,Assigned To,Category Short,Family Short,Nature,Origin,Origin Occurrence Time,First Occurrence Time,Last Occurrence Time,Duplicate Count,Uuid,Notes,Created,Modified"/>
    <generator field="priorityShort" class="gen_folder" affected="no">
       <param name="AlarmColumns" value="-ID,Message,Lifecycle State Short,Priority Short,Source Node Name,Assigned To,Category Short,Family Short,Nature,Origin,Origin Occurrence Time,First Occurrence Time,Last Occurrence Time,Duplicate Count,Uuid,Notes,Created,Modified"/>
    </generator>
  </group>

  <group name="Incidents By Lifecycle State" class="gen_folder">
    <param name="AlarmColumns" value="-ID,Message,Lifecycle State Short,Priority Short,Source Node Name,Assigned To,Category Short,Family Short,Nature,Origin,Origin Occurrence Time,First Occurrence Time,Last Occurrence Time,Duplicate Count,Uuid,Notes,Created,Modified"/>
    <generator field="lifecycleStateShort" class="gen_folder" affected="no">
       <param name="AlarmColumns" value="-ID,Message,Lifecycle State Short,Priority Short,Source Node Name,Assigned To,Category Short,Family Short,Nature,Origin,Origin Occurrence Time,First Occurrence Time,Last Occurrence Time,Duplicate Count,Uuid,Notes,Created,Modified"/>
    </generator>
  </group>

 </group>

</hierarchy>

=== ebhgw/sapmop509/database/examples/bscm/classesAndSubnetsByStructure.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE hierarchy PUBLIC "-//Novell, Inc.//DTD hierarchy 2.0//EN" "database/examples/hierarchy_2.0.dtd">
<!--
 Copyright (c) 2014 NetIQ Corporation.  All Rights Reserved.

 THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND TREATIES.  IT MAY NOT BE USED, COPIED,
 DISTRIBUTED, DISCLOSED, ADAPTED, PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT NETIQ'S
 PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE
 PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.

 NETIQ PROVIDES THE WORK "AS IS," WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING WITHOUT THE
 IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NETIQ,
 THE AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT LIABLE FOR ANY CLAIM,
 DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF,
 OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
-->
<hierarchy case="yes">

    <group name="Classes" class="gen_folder">

       <group name="By Source Class" class="gen_folder">
          <generator field="source.class" class="gen_folder" >
             <generator field="source.cn" class="gen_folder" >
             </generator>
          </generator>
       </group>
       <group name="By Structure Class" class="gen_folder">
          <generator field="structure.class" class="gen_folder" >
             <generator field="structure.cn" class="gen_folder" >
             </generator>
          </generator>
       </group>
    </group>

    <group name="Groupings" class="gen_folder">
       <group name="By Domain" class="gen_folder">

          <filter>
             <test type="script"><![CDATA[
               // @debug off

               // Figure out the domain.
               var domain = 'Uncategorized'
               var name = alarm.getField( 'structure.cn' )
               if( name != undefined )
               {
                  var nm = name.split( '\\.' )
                  if( nm.length >= 3 )
                  {
                     // Test first.  Is it a number?
                     var num = parseInt( nm[0] )
                     if( num != 0 && !isNaN( num ) )
                        domain = new java.lang.String( nm[ 0 ] + '.' + nm[ 1 ] + '.' + nm[ 2 ] )

                     // Not a dotted ip address, so use the last 2 or 3 sections for domain.
                     else
                     {
                        if( nm.length == 3 )
                           domain = new java.lang.String( nm[ nm.length - 2 ] + '.' + nm[ nm.length - 1 ] )
                        else
                           domain = new java.lang.String( nm[ nm.length - 3 ] + '.' + nm[ nm.length - 2 ] + '.' + nm[ nm.length - 1 ] )
                     }
                  }
               }
			   
			   // Figure out subnet.  In this case we are using the "ipAddress" property; it can be any valid property 
               // of the structure element which denotes the structure element's ip address
			   var subnet = 'No Network'
			   var val = alarm.getField( 'structure.ipAddress' )
			   if( val != undefined )
			   {
			      var lastDot = val.lastIndexOf( '.' )
				  if( lastDot > 0 )
				  {
				     subnet = val.substring( 0, lastDot ) + ' LAN'
				  }
			   }
			   
               // Set the domain and subnet of the alarm
               alarm.setField( 'domain', domain )
               alarm.setField( 'subnet', subnet )

               // Test succeeds
               true

             ]]></test>
          </filter>

          <generator field="domain" class="gen_folder" >
             <generator field="structure.cn" class="gen_folder" >
             </generator>
          </generator>
       </group>
	   <group name="By Network" class="gen_folder">
		  <generator field="subnet" class="gen_folder" >
			 <generator field="structure.cn" class="gen_folder" >
	       </generator>
	   </generator>
	</group>
    </group>
</hierarchy>

=== ebhgw/sapmop509/database/examples/TADDMHierarchy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hierarchy PUBLIC "-//Novell, Inc.//DTD hierarchy 2.0//EN" "database/examples/hierarchy_2.0.dtd">


<!--
 Copyright (c) 2014 NetIQ Corporation.  All Rights Reserved.

 THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND TREATIES.  IT MAY NOT BE USED, COPIED,
 DISTRIBUTED, DISCLOSED, ADAPTED, PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT NETIQ'S
 PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE
 PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.

 NETIQ PROVIDES THE WORK "AS IS," WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING WITHOUT THE
 IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NETIQ,
 THE AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT LIABLE FOR ANY CLAIM,
 DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF,
 OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
-->

<hierarchy>
<!-- 
      Please refer hierarchy_2.0.dtd in your BSM installation directory for details on the definition in this file.

      Using this TADDM hierarchy file (TADDMHierarchy.xml) a user of the TADDM adapter can define data
      to be displayed using the "field" attribute of the "generator" tag.

      The "field" attribute represents a predefined set of values that are used to represent certain
      types of data found in TADDM. The values and the data types they represent are these:
      
           applicationcomponent    Application Components discovered
           businessapplication     Business Applications discovered
           host                    Servers discovered
           networkdevice           Network Devices discovered
           software                Software Items discovered
           appcompsoftwareitem     A very useful amalgam of Application Component and Software Item

      Also, the "field" attribute of the "generator" tag allows the use of TADDM's fully qualified object names
      to identify items in a discovery. Examples of such names (although not limited to this list) are:

           com.collation.platform.model.topology.sys.hpux.HpUx
           com.collation.platform.model.topology.sys.UnitaryComputerSystem
           com.collation.platform.model.topology.sys.windows.WindowsComputerSystem

      Limited querying is also allowed to identify specific items in a discovery. Again the "field" attribute of
      the "generator" tag is be used. This means that by setting the "field" attribute to the following:

           ComputerSystem.OSRunning.OSName='Linux'

      that the computer systems which are running an operating system whose name is Linux are shown.

      The structure of the items follows the tag structure that a query of this form would return:

           SELECT * ComputerSystem WHERE OSRunning.OSName == 'Linux'

      This previous query employs TADDM's Model Query Language and would return as output from the query an OSName
      XML tag nested within a OSRunning XML tag which in turn is nested within a ComputerSystem XML tag. Hierarchically,
      that would look like this:

       ComputerSystem XML tag
      	 OSRunning XML tag
      		 OSName XML tag

      Knowing this structure, queries can be properly formed.

     -->

	<group class="formula_organizations" name="Discovered Objects" > 
		<!-- Start Default Layout -->
		<group class="gen_folder" name="Business Applications">
		  <generator class_from_field="icon_name" field="businessapplication"/> 
		</group>

		<group class="gen_folder" name="Hosts">
		  <generator class_from_field="icon_name" field="host"/> 
		</group>

		<group class="gen_folder" name="Application Components">
		  <generator class_from_field="icon_name" field="applicationcomponent"/>
		</group>

		<group class="gen_folder" name="Network Devices">
		  <generator class_from_field="icon_name" field="networkdevice"/> 
		</group>
		<!-- End Default Layout -->
	</group>
</hierarchy>
